version: "3"
services:
  # mongo db
  nosql-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./database/mongo:/data/db
    networks:
      - backend

  mysql-db:
    container_name: "mysql-db"
    platform: linux/amd64
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    volumes:
      - ./database/mysql:/data/db
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backend

  # gateway-config
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./gateway-config
    container_name: gateway
    depends_on:
      - posts-services
      - category-services
    ports:
      - 8000:80
    networks:
      - backend

  # posts-services
  posts-services:
    build:
      dockerfile: Dockerfile
      context: ./posts-services
    container_name: posts-services
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./:/app
      - /app/posts-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./posts-services/.env.dev

  # category-services
  category-services:
    build:
      dockerfile: Dockerfile
      context: ./category-services
    container_name: category-services
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./:/app
      - /app/category-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./category-services/.env.dev

  # users-services
  users-services:
    build:
      dockerfile: Dockerfile
      context: ./users-services
    container_name: users-services
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - "mysql-db"
    volumes:
      - ./:/app
      - /app/users-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./users-services/.env.dev

networks:
  backend:
    driver: bridge