version: "3"
services:
  # mongo db
  nosql-db:
    image: mongo:5
    platform: linux/amd64
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./database/mongo:/data/db
    networks:
      - backend

  mysql-db:
    container_name: "mysql-db"
    platform: linux/amd64
    image: mysql:5.7.31
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - "3333:3306"
    environment:
      - MYSQL_DATABASE=admin_blog
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backend

  # gateway-config
  nginx-proxy:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./gateway-config
    container_name: gateway
    depends_on:
      - posts-services
      - category-services
      - users-services
      - favourites-services
      - comments-services
    ports:
      - 8000:80
    networks:
      - backend

  # posts-services
  posts-services:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./posts-services
    container_name: posts-services
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./:/app
      - /app/posts-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./posts-services/.env.dev

  # category-services
  category-services:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./category-services
    container_name: category-services
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./:/app
      - /app/category-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./category-services/.env.dev

  # users-services
  users-services:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./users-services
    container_name: users-services
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - "mysql-db"
    volumes:
      - ./:/app
      - /app/users-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./users-services/.env.dev

  # favourites-services
  favourites-services:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./favourites-services
    container_name: favourites-services
    ports:
      - "3003:3003"
    restart: always
    depends_on:
      - "mysql-db"
    volumes:
      - ./:/app
      - /app/favourites-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./favourites-services/.env.dev

  # comments-services
  comments-services:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./comments-services
    container_name: comments-services
    ports:
      - "3004:3004"
    restart: always
    depends_on:
      - "mysql-db"
    volumes:
      - ./:/app
      - /app/comments-services/node_modules
    networks:
      - backend
    # env_file:
    #   - ./comments-services/.env.dev

networks:
  backend:
    driver: bridge